### PR TITLE
Add zoom control

### LINKED ISSUE #21: Change font size with Control +/-
The default font size factor in Dillo is fixed until the browser is closed and open again. However, some pages have very small font sizes and it would be convenient if we can allow the factor to be modified live.

The shortcuts <kbd>Control</kbd><kbd>+</kbd> and <kbd>Control</kbd><kbd>-</kbd> are typically used for this end in other browsers.

### PR DESCRIPTION
**Pull request by rodarima**
Fixes #21

### CODE REVIEW

**Comment by rodarima** [comment]
Control-+ doesn't seem work in US keyboard layouts.

**Comment by niutech** [comment]
@rodarima Please use `Ctrl =` instead of `Ctrl +`, so that it doesn't require pressing `Shift`, which is consistent with major web browsers.

Also please add `Ctrl 0` to reset zoom to 100%.

**Comment by rodarima** [comment]
> @rodarima Please use `Ctrl =` instead of `Ctrl +`, so that it doesn't require pressing `Shift`, which is consistent with major web browsers.

It should work now both for US and EU keyboards. Both Ctrl + and Ctrl = cause a zoom increase.

> Also please add `Ctrl 0` to reset zoom to 100%.

Should be working too.

**Comment by niutech** [comment]
@rodarima Thank you!

**Pull request merged**
